spring:
  application:
    name: todo

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://192.168.0.100:5432/codeschdb
    username: codesch
    password: codeschpwd