spring:
  application:
    name: project

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
      generate_statistics: true

  datasource:
    url: jdbc:postgresql://localhost:5432/project_db
    username: songheesu
    password: 10040160
    driver-class-name: org.postgresql.Driver


  #autoconfigure:
      #exclude:
        #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

      #datasource:
    #url: jdbc:postgresql://localhost:5432/todolist
    #username: songheesu
    #password: 10040160
    #driver-class-name: org.postgresql.Driver
  #kakao:
    #key:
      #client_id: b23af313ad89940e19a6df68ec84a94c
    #redirect_uri: https://to-do-list-client-two.vercel.app/kakao/callback/
